## Decision tree classification

In [4]:
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [5]:
df = pd.read_csv(r"C:\Users\admin\Desktop\Machine learning\Day-18\daily_weather.csv")

In [6]:
df

,number,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm
0,0,918.060000,74.822000,271.100000,2.080354,295.400000,2.863283,0.0,0.0,42.420000,36.160000
1,1,917.347688,71.403843,101.935179,2.443009,140.471548,3.533324,0.0,0.0,24.328697,19.426597
2,2,923.040000,60.638000,51.000000,17.067852,63.700000,22.100967,0.0,20.0,8.900000,14.460000
3,3,920.502751,70.138895,198.832133,4.337363,211.203341,5.190045,0.0,0.0,12.189102,12.742547
4,4,921.160000,44.294000,277.800000,1.856660,136.500000,2.863283,8.9,14730.0,92.410000,76.740000
...,...,...,...,...,...,...,...,...,...,...,...
1090,1090,918.900000,63.104000,192.900000,3.869906,207.300000,5.212070,0.0,0.0,26.020000,38.180000
1091,1091,918.710000,49.568000,241.600000,1.811921,227.400000,2.371156,0.0,0.0,90.350000,73.340000
1092,1092,916.600000,71.096000,189.300000,3.064608,200.800000,3.892276,0.0,0.0,45.590000,52.310000
1093,1093,912.600000,58.406000,172.700000,3.825167,189.100000,4.764682,0.0,0.0,64.840000,58.280000
1094,1094,921.530000,77.702000,97.100000,3.265932,125.900000,4.451511,0.0,0.0,14.560000,15.100000

In [16]:
df.columns

Index(['number', 'air_pressure_9am', 'air_temp_9am', 'avg_wind_direction_9am',
       'avg_wind_speed_9am', 'max_wind_direction_9am', 'max_wind_speed_9am',
       'rain_accumulation_9am', 'rain_duration_9am', 'relative_humidity_9am',
       'relative_humidity_3pm'],
      dtype='object')

In [17]:
df.info

<bound method DataFrame.info of       number  air_pressure_9am  air_temp_9am  avg_wind_direction_9am  \
0          0        918.060000     74.822000              271.100000
1          1        917.347688     71.403843              101.935179
2          2        923.040000     60.638000               51.000000
3          3        920.502751     70.138895              198.832133
4          4        921.160000     44.294000              277.800000
...      ...               ...           ...                     ...
1090    1090        918.900000     63.104000              192.900000
1091    1091        918.710000     49.568000              241.600000
1092    1092        916.600000     71.096000              189.300000
1093    1093        912.600000     58.406000              172.700000
1094    1094        921.530000     77.702000               97.100000

      avg_wind_speed_9am  max_wind_direction_9am  max_wind_speed_9am  \
0               2.080354              295.400000            2.863283
1               2.443009              140.471548            3.533324
2              17.067852               63.700000           22.100967
3               4.337363              211.203341            5.190045
4               1.856660              136.500000            2.863283
...                  ...                     ...                 ...
1090            3.869906              207.300000            5.212070
1091            1.811921              227.400000            2.371156
1092            3.064608              200.800000            3.892276
1093            3.825167              189.100000            4.764682
1094            3.265932              125.900000            4.451511

      rain_accumulation_9am  rain_duration_9am  relative_humidity_9am  \
0                       0.0                0.0              42.420000
1                       0.0                0.0              24.328697
2                       0.0               20.0               8.900000
3                       0.0                0.0              12.189102
4                       8.9            14730.0              92.410000
...                     ...                ...                    ...
1090                    0.0                0.0              26.020000
1091                    0.0                0.0              90.350000
1092                    0.0                0.0              45.590000
1093                    0.0                0.0              64.840000
1094                    0.0                0.0              14.560000

      relative_humidity_3pm
0                 36.160000
1                 19.426597
2                 14.460000
3                 12.742547
4                 76.740000
...                     ...
1090              38.180000
1091              73.340000
1092              52.310000
1093              58.280000
1094              15.100000

[1095 rows x 11 columns]>

In [18]:
df.isnull

<bound method DataFrame.isnull of       number  air_pressure_9am  air_temp_9am  avg_wind_direction_9am  \
0          0        918.060000     74.822000              271.100000
1          1        917.347688     71.403843              101.935179
2          2        923.040000     60.638000               51.000000
3          3        920.502751     70.138895              198.832133
4          4        921.160000     44.294000              277.800000
...      ...               ...           ...                     ...
1090    1090        918.900000     63.104000              192.900000
1091    1091        918.710000     49.568000              241.600000
1092    1092        916.600000     71.096000              189.300000
1093    1093        912.600000     58.406000              172.700000
1094    1094        921.530000     77.702000               97.100000

      avg_wind_speed_9am  max_wind_direction_9am  max_wind_speed_9am  \
0               2.080354              295.400000            2.863283
1               2.443009              140.471548            3.533324
2              17.067852               63.700000           22.100967
3               4.337363              211.203341            5.190045
4               1.856660              136.500000            2.863283
...                  ...                     ...                 ...
1090            3.869906              207.300000            5.212070
1091            1.811921              227.400000            2.371156
1092            3.064608              200.800000            3.892276
1093            3.825167              189.100000            4.764682
1094            3.265932              125.900000            4.451511

      rain_accumulation_9am  rain_duration_9am  relative_humidity_9am  \
0                       0.0                0.0              42.420000
1                       0.0                0.0              24.328697
2                       0.0               20.0               8.900000
3                       0.0                0.0              12.189102
4                       8.9            14730.0              92.410000
...                     ...                ...                    ...
1090                    0.0                0.0              26.020000
1091                    0.0                0.0              90.350000
1092                    0.0                0.0              45.590000
1093                    0.0                0.0              64.840000
1094                    0.0                0.0              14.560000

      relative_humidity_3pm
0                 36.160000
1                 19.426597
2                 14.460000
3                 12.742547
4                 76.740000
...                     ...
1090              38.180000
1091              73.340000
1092              52.310000
1093              58.280000
1094              15.100000

[1095 rows x 11 columns]>

In [23]:
df.isnull().sum()

number                    0
air_pressure_9am          3
air_temp_9am              5
avg_wind_direction_9am    4
avg_wind_speed_9am        3
max_wind_direction_9am    3
max_wind_speed_9am        4
rain_accumulation_9am     6
rain_duration_9am         3
relative_humidity_9am     0
relative_humidity_3pm     0
dtype: int64

In [28]:
df.fillna

<bound method NDFrame.fillna of       number  air_pressure_9am  air_temp_9am  avg_wind_direction_9am  \
0          0        918.060000     74.822000              271.100000
1          1        917.347688     71.403843              101.935179
2          2        923.040000     60.638000               51.000000
3          3        920.502751     70.138895              198.832133
4          4        921.160000     44.294000              277.800000
...      ...               ...           ...                     ...
1090    1090        918.900000     63.104000              192.900000
1091    1091        918.710000     49.568000              241.600000
1092    1092        916.600000     71.096000              189.300000
1093    1093        912.600000     58.406000              172.700000
1094    1094        921.530000     77.702000               97.100000

      avg_wind_speed_9am  max_wind_direction_9am  max_wind_speed_9am  \
0               2.080354              295.400000            2.863283
1               2.443009              140.471548            3.533324
2              17.067852               63.700000           22.100967
3               4.337363              211.203341            5.190045
4               1.856660              136.500000            2.863283
...                  ...                     ...                 ...
1090            3.869906              207.300000            5.212070
1091            1.811921              227.400000            2.371156
1092            3.064608              200.800000            3.892276
1093            3.825167              189.100000            4.764682
1094            3.265932              125.900000            4.451511

      rain_accumulation_9am  rain_duration_9am  relative_humidity_9am  \
0                       0.0                0.0              42.420000
1                       0.0                0.0              24.328697
2                       0.0               20.0               8.900000
3                       0.0                0.0              12.189102
4                       8.9            14730.0              92.410000
...                     ...                ...                    ...
1090                    0.0                0.0              26.020000
1091                    0.0                0.0              90.350000
1092                    0.0                0.0              45.590000
1093                    0.0                0.0              64.840000
1094                    0.0                0.0              14.560000

      relative_humidity_3pm
0                 36.160000
1                 19.426597
2                 14.460000
3                 12.742547
4                 76.740000
...                     ...
1090              38.180000
1091              73.340000
1092              52.310000
1093              58.280000
1094              15.100000

[1095 rows x 11 columns]>

Convert to a Classification Task

In [31]:
clean_df = df.copy()
clean_df['high_humidity_label'] = (clean_df['relative_humidity_3pm'] > 24.99)*1
print(clean_df['high_humidity_label'])

0       1
1       0
2       0
3       0
4       1
       ..
1090    1
1091    1
1092    1
1093    1
1094    0
Name: high_humidity_label, Length: 1095, dtype: int32

Target is stored in 'y'.

In [32]:
y=clean_df[['high_humidity_label']].copy()

In [37]:
y.head()

   high_humidity_label
0                    1
1                    0
2                    0
3                    0
4                    1

In [36]:
clean_df['relative_humidity_3pm'].head()
y.head()

   high_humidity_label
0                    1
1                    0
2                    0
3                    0
4                    1

use 9am sensor signals as features humidity at 3pm

In [38]:
morning_features = ['air_pressure_9am','air_temp_9am','avg_wind_direction_9am','avg_wind_speed_9am',
        'max_wind_direction_9am','max_wind_speed_9am','rain_accumulation_9am',
        'rain_duration_9am']

In [40]:
X = clean_df[morning_features].copy()

In [41]:
X.columns

Index(['air_pressure_9am', 'air_temp_9am', 'avg_wind_direction_9am',
       'avg_wind_speed_9am', 'max_wind_direction_9am', 'max_wind_speed_9am',
       'rain_accumulation_9am', 'rain_duration_9am'],
      dtype='object')

In [42]:
y.columns

Index(['high_humidity_label'], dtype='object')

perform test and train split

In [79]:
X_train,X_test,y_train,y_test  = train_test_split(X,y, test_size=0.33,random_state=0)

fit on train

In [80]:
humidity_classifier = DecisionTreeClassifier(max_leaf_nodes=10, random_state=0)
humidity_classifier.fit(X_train, y_train)

DecisionTreeClassifier(max_leaf_nodes=10, random_state=0)

In [81]:
type(humidity_classifier)

sklearn.tree._classes.DecisionTreeClassifier

Predict in Test Set

In [82]:
predictions = humidity_classifier.predict(X_test)

In [83]:
predictions[:10]

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [84]:
y_test['high_humidity_label'][:10]

784    1
741    0
747    1
987    0
479    1
27     1
159    1
356    1
320    1
351    1
Name: high_humidity_label, dtype: int32

Measure accuracy of the classifier

In [85]:
accuracy_score(y_true = y_test, y_pred = predictions)

0.7955801104972375

## Data preprocessing

In [93]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [94]:
df = pd.read_csv(r"C:\Users\admin\Desktop\Machine learning\Day-18\avito.csv")

In [95]:
df

,item_id,user_id,region,city,parent_category_name,category_name,param_1,param_2,param_3,title,description,price,item_seq_number,activation_date,user_type,image,image_top_1,deal_probability
0,b912c3c6a6ad,e00f8ff2eaf9,Свердловская область,Екатеринбург,Личные вещи,Товары для детей и игрушки,Постельные принадлежности,NaN,NaN,Кокоби(кокон для сна),"Кокон для сна малыша,пользовались меньше месяц...",400.0,2,2017-03-28,Private,d10c7e016e03247a3bf2d13348fe959fe6f436c1caf64c...,1008.0,0.12789
1,2dac0150717d,39aeb48f0017,Самарская область,Самара,Для дома и дачи,Мебель и интерьер,Другое,NaN,NaN,Стойка для Одежды,"Стойка для одежды, под вешалки. С бутика.",3000.0,19,2017-03-26,Private,79c9392cc51a9c81c6eb91eceb8e552171db39d7142700...,692.0,0.00000
2,ba83aefab5dc,91e2f88dd6e3,Ростовская область,Ростов-на-Дону,Бытовая электроника,Аудио и видео,"Видео, DVD и Blu-ray плееры",NaN,NaN,Philips bluray,"В хорошем состоянии, домашний кинотеатр с blu ...",4000.0,9,2017-03-20,Private,b7f250ee3f39e1fedd77c141f273703f4a9be59db4b48a...,3032.0,0.43177
3,02996f1dd2ea,bf5cccea572d,Татарстан,Набережные Челны,Личные вещи,Товары для детей и игрушки,Автомобильные кресла,NaN,NaN,Автокресло,Продам кресло от0-25кг,2200.0,286,2017-03-25,Company,e6ef97e0725637ea84e3d203e82dadb43ed3cc0a1c8413...,796.0,0.80323
4,7c90be56d2ab,ef50846afc0b,Волгоградская область,Волгоград,Транспорт,Автомобили,С пробегом,ВАЗ (LADA),2110,"ВАЗ 2110, 2003",Все вопросы по телефону.,40000.0,3,2017-03-16,Private,54a687a3a0fc1d68aed99bdaaf551c5c70b761b16fd0a2...,2264.0,0.20797
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,401d5fa8e55d,b5fe6a389cc4,Ярославская область,Ярославль,Хобби и отдых,Спорт и отдых,Игры с мячом,NaN,NaN,Продам бутсы Adidas,продам бутсы в отличном состоянии.отыграл 3 тр...,NaN,27,2017-03-27,Private,7c640fb4b6b4066c54e082193b66bedaedfee5e4d12975...,640.0,0.00000
996,4b136de2c16a,f57df929a284,Воронежская область,Воронеж,Бытовая электроника,"Игры, приставки и программы",Игры для приставок,NaN,NaN,Продам диск lara croft на psp,NaN,350.0,142,2017-03-27,Company,0a7686a2e05ca2dc0470e550f1f03b1eddee7919d363ca...,2888.0,0.00000
997,a65090f39f50,8673d0037023,Свердловская область,Монетный,Недвижимость,"Дома, дачи, коттеджи",Продам,Коттедж,NaN,Коттедж 150 м² на участке 12 сот.,Продается чудесный коттедж в экологически чист...,5900000.0,5830,2017-03-18,Shop,9061df217dd8f2b338e2645d52b09af6143677d011002a...,1376.0,0.07725
998,53e0aa75cecd,fbfe3f73586d,Башкортостан,Ишимбай,Транспорт,Автомобили,С пробегом,Hyundai,i30,"Hyundai i30, 2012",Продается автомобиль Hyundai i30. Был куплен ...,550000.0,1,2017-03-20,Private,c7fe551884576cb8b1bb9bbfe216b3e0b437d6b2208deb...,1118.0,0.10521
999,211a7d242f97,b3e017bd61eb,Самарская область,Самара,Для дома и дачи,Ремонт и строительство,Окна и балконы,NaN,NaN,Породам окно,"Глухое 1кам32 с.пакет, ш650в1440. Новое не под...",2000.0,32,2017-03-24,Private,a68483a58dfbf3b7abf95dfe623651aa45dc211dbb2992...,1405.0,0.00000

In [96]:
df.isnull().sum()

item_id                   0
user_id                   0
region                    0
city                      0
parent_category_name      0
category_name             0
param_1                  44
param_2                 447
param_3                 594
title                     0
description              67
price                    65
item_seq_number           0
activation_date           0
user_type                 0
image                    79
image_top_1              79
deal_probability          0
dtype: int64

In [97]:
df.fillna

<bound method NDFrame.fillna of           item_id       user_id                 region              city  \
0    b912c3c6a6ad  e00f8ff2eaf9   Свердловская область      Екатеринбург
1    2dac0150717d  39aeb48f0017      Самарская область            Самара
2    ba83aefab5dc  91e2f88dd6e3     Ростовская область    Ростов-на-Дону
3    02996f1dd2ea  bf5cccea572d              Татарстан  Набережные Челны
4    7c90be56d2ab  ef50846afc0b  Волгоградская область         Волгоград
..            ...           ...                    ...               ...
995  401d5fa8e55d  b5fe6a389cc4    Ярославская область         Ярославль
996  4b136de2c16a  f57df929a284    Воронежская область           Воронеж
997  a65090f39f50  8673d0037023   Свердловская область          Монетный
998  53e0aa75cecd  fbfe3f73586d           Башкортостан           Ишимбай
999  211a7d242f97  b3e017bd61eb      Самарская область            Самара

    parent_category_name                category_name  \
0            Личные вещи   Товары для детей и игрушки
1        Для дома и дачи            Мебель и интерьер
2    Бытовая электроника                Аудио и видео
3            Личные вещи   Товары для детей и игрушки
4              Транспорт                   Автомобили
..                   ...                          ...
995        Хобби и отдых                Спорт и отдых
996  Бытовая электроника  Игры, приставки и программы
997         Недвижимость         Дома, дачи, коттеджи
998            Транспорт                   Автомобили
999      Для дома и дачи       Ремонт и строительство

                         param_1     param_2 param_3  \
0      Постельные принадлежности         NaN     NaN
1                         Другое         NaN     NaN
2    Видео, DVD и Blu-ray плееры         NaN     NaN
3           Автомобильные кресла         NaN     NaN
4                     С пробегом  ВАЗ (LADA)    2110
..                           ...         ...     ...
995                 Игры с мячом         NaN     NaN
996           Игры для приставок         NaN     NaN
997                       Продам     Коттедж     NaN
998                   С пробегом     Hyundai     i30
999               Окна и балконы         NaN     NaN

                                 title  \
0                Кокоби(кокон для сна)
1                    Стойка для Одежды
2                       Philips bluray
3                           Автокресло
4                       ВАЗ 2110, 2003
..                                 ...
995                Продам бутсы Adidas
996      Продам диск lara croft на psp
997  Коттедж 150 м² на участке 12 сот.
998                  Hyundai i30, 2012
999                       Породам окно

                                           description      price  \
0    Кокон для сна малыша,пользовались меньше месяц...      400.0
1            Стойка для одежды, под вешалки. С бутика.     3000.0
2    В хорошем состоянии, домашний кинотеатр с blu ...     4000.0
3                               Продам кресло от0-25кг     2200.0
4                             Все вопросы по телефону.    40000.0
..                                                 ...        ...
995  продам бутсы в отличном состоянии.отыграл 3 тр...        NaN
996                                                NaN      350.0
997  Продается чудесный коттедж в экологически чист...  5900000.0
998  Продается автомобиль  Hyundai i30. Был куплен ...   550000.0
999  Глухое 1кам32 с.пакет, ш650в1440. Новое не под...     2000.0

     item_seq_number activation_date user_type  \
0                  2      2017-03-28   Private
1                 19      2017-03-26   Private
2                  9      2017-03-20   Private
3                286      2017-03-25   Company
4                  3      2017-03-16   Private
..               ...             ...       ...
995               27      2017-03-27   Private
996              142      2017-03-27   Company
997             5830      2017-03-18      Shop
998                1      2017-03-20   Private
999               32      2017-03-24   Private

                                                 image  image_top_1  \
0    d10c7e016e03247a3bf2d13348fe959fe6f436c1caf64c...       1008.0
1    79c9392cc51a9c81c6eb91eceb8e552171db39d7142700...        692.0
2    b7f250ee3f39e1fedd77c141f273703f4a9be59db4b48a...       3032.0
3    e6ef97e0725637ea84e3d203e82dadb43ed3cc0a1c8413...        796.0
4    54a687a3a0fc1d68aed99bdaaf551c5c70b761b16fd0a2...       2264.0
..                                                 ...          ...
995  7c640fb4b6b4066c54e082193b66bedaedfee5e4d12975...        640.0
996  0a7686a2e05ca2dc0470e550f1f03b1eddee7919d363ca...       2888.0
997  9061df217dd8f2b338e2645d52b09af6143677d011002a...       1376.0
998  c7fe551884576cb8b1bb9bbfe216b3e0b437d6b2208deb...       1118.0
999  a68483a58dfbf3b7abf95dfe623651aa45dc211dbb2992...       1405.0

     deal_probability
0             0.12789
1             0.00000
2             0.43177
3             0.80323
4             0.20797
..                ...
995           0.00000
996           0.00000
997           0.07725
998           0.10521
999           0.00000

[1000 rows x 18 columns]>

In [98]:
df.columns

Index(['item_id', 'user_id', 'region', 'city', 'parent_category_name',
       'category_name', 'param_1', 'param_2', 'param_3', 'title',
       'description', 'price', 'item_seq_number', 'activation_date',
       'user_type', 'image', 'image_top_1', 'deal_probability'],
      dtype='object')

In [99]:
df.info

<bound method DataFrame.info of           item_id       user_id                 region              city  \
0    b912c3c6a6ad  e00f8ff2eaf9   Свердловская область      Екатеринбург
1    2dac0150717d  39aeb48f0017      Самарская область            Самара
2    ba83aefab5dc  91e2f88dd6e3     Ростовская область    Ростов-на-Дону
3    02996f1dd2ea  bf5cccea572d              Татарстан  Набережные Челны
4    7c90be56d2ab  ef50846afc0b  Волгоградская область         Волгоград
..            ...           ...                    ...               ...
995  401d5fa8e55d  b5fe6a389cc4    Ярославская область         Ярославль
996  4b136de2c16a  f57df929a284    Воронежская область           Воронеж
997  a65090f39f50  8673d0037023   Свердловская область          Монетный
998  53e0aa75cecd  fbfe3f73586d           Башкортостан           Ишимбай
999  211a7d242f97  b3e017bd61eb      Самарская область            Самара

    parent_category_name                category_name  \
0            Личные вещи   Товары для детей и игрушки
1        Для дома и дачи            Мебель и интерьер
2    Бытовая электроника                Аудио и видео
3            Личные вещи   Товары для детей и игрушки
4              Транспорт                   Автомобили
..                   ...                          ...
995        Хобби и отдых                Спорт и отдых
996  Бытовая электроника  Игры, приставки и программы
997         Недвижимость         Дома, дачи, коттеджи
998            Транспорт                   Автомобили
999      Для дома и дачи       Ремонт и строительство

                         param_1     param_2 param_3  \
0      Постельные принадлежности         NaN     NaN
1                         Другое         NaN     NaN
2    Видео, DVD и Blu-ray плееры         NaN     NaN
3           Автомобильные кресла         NaN     NaN
4                     С пробегом  ВАЗ (LADA)    2110
..                           ...         ...     ...
995                 Игры с мячом         NaN     NaN
996           Игры для приставок         NaN     NaN
997                       Продам     Коттедж     NaN
998                   С пробегом     Hyundai     i30
999               Окна и балконы         NaN     NaN

                                 title  \
0                Кокоби(кокон для сна)
1                    Стойка для Одежды
2                       Philips bluray
3                           Автокресло
4                       ВАЗ 2110, 2003
..                                 ...
995                Продам бутсы Adidas
996      Продам диск lara croft на psp
997  Коттедж 150 м² на участке 12 сот.
998                  Hyundai i30, 2012
999                       Породам окно

                                           description      price  \
0    Кокон для сна малыша,пользовались меньше месяц...      400.0
1            Стойка для одежды, под вешалки. С бутика.     3000.0
2    В хорошем состоянии, домашний кинотеатр с blu ...     4000.0
3                               Продам кресло от0-25кг     2200.0
4                             Все вопросы по телефону.    40000.0
..                                                 ...        ...
995  продам бутсы в отличном состоянии.отыграл 3 тр...        NaN
996                                                NaN      350.0
997  Продается чудесный коттедж в экологически чист...  5900000.0
998  Продается автомобиль  Hyundai i30. Был куплен ...   550000.0
999  Глухое 1кам32 с.пакет, ш650в1440. Новое не под...     2000.0

     item_seq_number activation_date user_type  \
0                  2      2017-03-28   Private
1                 19      2017-03-26   Private
2                  9      2017-03-20   Private
3                286      2017-03-25   Company
4                  3      2017-03-16   Private
..               ...             ...       ...
995               27      2017-03-27   Private
996              142      2017-03-27   Company
997             5830      2017-03-18      Shop
998                1      2017-03-20   Private
999               32      2017-03-24   Private

                                                 image  image_top_1  \
0    d10c7e016e03247a3bf2d13348fe959fe6f436c1caf64c...       1008.0
1    79c9392cc51a9c81c6eb91eceb8e552171db39d7142700...        692.0
2    b7f250ee3f39e1fedd77c141f273703f4a9be59db4b48a...       3032.0
3    e6ef97e0725637ea84e3d203e82dadb43ed3cc0a1c8413...        796.0
4    54a687a3a0fc1d68aed99bdaaf551c5c70b761b16fd0a2...       2264.0
..                                                 ...          ...
995  7c640fb4b6b4066c54e082193b66bedaedfee5e4d12975...        640.0
996  0a7686a2e05ca2dc0470e550f1f03b1eddee7919d363ca...       2888.0
997  9061df217dd8f2b338e2645d52b09af6143677d011002a...       1376.0
998  c7fe551884576cb8b1bb9bbfe216b3e0b437d6b2208deb...       1118.0
999  a68483a58dfbf3b7abf95dfe623651aa45dc211dbb2992...       1405.0

     deal_probability
0             0.12789
1             0.00000
2             0.43177
3             0.80323
4             0.20797
..                ...
995           0.00000
996           0.00000
997           0.07725
998           0.10521
999           0.00000

[1000 rows x 18 columns]>

In [101]:
df.tail()

,item_id,user_id,region,city,parent_category_name,category_name,param_1,param_2,param_3,title,description,price,item_seq_number,activation_date,user_type,image,image_top_1,deal_probability
995,401d5fa8e55d,b5fe6a389cc4,Ярославская область,Ярославль,Хобби и отдых,Спорт и отдых,Игры с мячом,NaN,NaN,Продам бутсы Adidas,продам бутсы в отличном состоянии.отыграл 3 тр...,NaN,27,2017-03-27,Private,7c640fb4b6b4066c54e082193b66bedaedfee5e4d12975...,640.0,0.00000
996,4b136de2c16a,f57df929a284,Воронежская область,Воронеж,Бытовая электроника,"Игры, приставки и программы",Игры для приставок,NaN,NaN,Продам диск lara croft на psp,NaN,350.0,142,2017-03-27,Company,0a7686a2e05ca2dc0470e550f1f03b1eddee7919d363ca...,2888.0,0.00000
997,a65090f39f50,8673d0037023,Свердловская область,Монетный,Недвижимость,"Дома, дачи, коттеджи",Продам,Коттедж,NaN,Коттедж 150 м² на участке 12 сот.,Продается чудесный коттедж в экологически чист...,5900000.0,5830,2017-03-18,Shop,9061df217dd8f2b338e2645d52b09af6143677d011002a...,1376.0,0.07725
998,53e0aa75cecd,fbfe3f73586d,Башкортостан,Ишимбай,Транспорт,Автомобили,С пробегом,Hyundai,i30,"Hyundai i30, 2012",Продается автомобиль Hyundai i30. Был куплен ...,550000.0,1,2017-03-20,Private,c7fe551884576cb8b1bb9bbfe216b3e0b437d6b2208deb...,1118.0,0.10521
999,211a7d242f97,b3e017bd61eb,Самарская область,Самара,Для дома и дачи,Ремонт и строительство,Окна и балконы,NaN,NaN,Породам окно,"Глухое 1кам32 с.пакет, ш650в1440. Новое не под...",2000.0,32,2017-03-24,Private,a68483a58dfbf3b7abf95dfe623651aa45dc211dbb2992...,1405.0,0.00000

In [102]:
expensive_items = df[df['price'] > 1000]  # performing eda=exploratory data analysis
expensive_items

,item_id,user_id,region,city,parent_category_name,category_name,param_1,param_2,param_3,title,description,price,item_seq_number,activation_date,user_type,image,image_top_1,deal_probability
1,2dac0150717d,39aeb48f0017,Самарская область,Самара,Для дома и дачи,Мебель и интерьер,Другое,NaN,NaN,Стойка для Одежды,"Стойка для одежды, под вешалки. С бутика.",3000.0,19,2017-03-26,Private,79c9392cc51a9c81c6eb91eceb8e552171db39d7142700...,692.0,0.00000
2,ba83aefab5dc,91e2f88dd6e3,Ростовская область,Ростов-на-Дону,Бытовая электроника,Аудио и видео,"Видео, DVD и Blu-ray плееры",NaN,NaN,Philips bluray,"В хорошем состоянии, домашний кинотеатр с blu ...",4000.0,9,2017-03-20,Private,b7f250ee3f39e1fedd77c141f273703f4a9be59db4b48a...,3032.0,0.43177
3,02996f1dd2ea,bf5cccea572d,Татарстан,Набережные Челны,Личные вещи,Товары для детей и игрушки,Автомобильные кресла,NaN,NaN,Автокресло,Продам кресло от0-25кг,2200.0,286,2017-03-25,Company,e6ef97e0725637ea84e3d203e82dadb43ed3cc0a1c8413...,796.0,0.80323
4,7c90be56d2ab,ef50846afc0b,Волгоградская область,Волгоград,Транспорт,Автомобили,С пробегом,ВАЗ (LADA),2110,"ВАЗ 2110, 2003",Все вопросы по телефону.,40000.0,3,2017-03-16,Private,54a687a3a0fc1d68aed99bdaaf551c5c70b761b16fd0a2...,2264.0,0.20797
5,51e0962387f7,bbfad0b1ad0a,Татарстан,Чистополь,Личные вещи,Товары для детей и игрушки,Автомобильные кресла,NaN,NaN,Авто люлька,В хорошем состоянии,1300.0,9,2017-03-28,Private,eb6ad1231c59d3dc7e4020e724ffe8e4d302023ddcbb99...,796.0,0.80323
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,442432ea065b,ef2765b65cae,Воронежская область,Воронеж,Бытовая электроника,Телефоны,Номера и SIM-карты,NaN,NaN,Красивый номер мегафон,Продам красивый номер:восемь девятьсот двадцат...,12000.0,4,2017-03-16,Private,NaN,NaN,0.00000
992,5ca79042c44d,1f120cac985a,Краснодарский край,Анапа,Личные вещи,"Одежда, обувь, аксессуары",Женская одежда,Платья и юбки,40–42 (XS),Юбка Kira Plastinina,"В идеальном состоянии, на талию 160-165",2300.0,26,2017-03-22,Private,131ae8c08c2ad30fc342cfbada3db3e2356cd7fe79a9ec...,81.0,0.00000
997,a65090f39f50,8673d0037023,Свердловская область,Монетный,Недвижимость,"Дома, дачи, коттеджи",Продам,Коттедж,NaN,Коттедж 150 м² на участке 12 сот.,Продается чудесный коттедж в экологически чист...,5900000.0,5830,2017-03-18,Shop,9061df217dd8f2b338e2645d52b09af6143677d011002a...,1376.0,0.07725
998,53e0aa75cecd,fbfe3f73586d,Башкортостан,Ишимбай,Транспорт,Автомобили,С пробегом,Hyundai,i30,"Hyundai i30, 2012",Продается автомобиль Hyundai i30. Был куплен ...,550000.0,1,2017-03-20,Private,c7fe551884576cb8b1bb9bbfe216b3e0b437d6b2208deb...,1118.0,0.10521
999,211a7d242f97,b3e017bd61eb,Самарская область,Самара,Для дома и дачи,Ремонт и строительство,Окна и балконы,NaN,NaN,Породам окно,"Глухое 1кам32 с.пакет, ш650в1440. Новое не под...",2000.0,32,2017-03-24,Private,a68483a58dfbf3b7abf95dfe623651aa45dc211dbb2992...,1405.0,0.00000

In [109]:
print("df_avito.shape: {}".format(df.shape))
print("expensive_items.shape: {}".format(expensive_items.shape))

df_avito.shape: (1000, 18)
expensive_items.shape: (480, 18)

In [111]:
items_with_price = df[df['price'] != np.nan]
items_with_price

,item_id,user_id,region,city,parent_category_name,category_name,param_1,param_2,param_3,title,description,price,item_seq_number,activation_date,user_type,image,image_top_1,deal_probability
0,b912c3c6a6ad,e00f8ff2eaf9,Свердловская область,Екатеринбург,Личные вещи,Товары для детей и игрушки,Постельные принадлежности,NaN,NaN,Кокоби(кокон для сна),"Кокон для сна малыша,пользовались меньше месяц...",400.0,2,2017-03-28,Private,d10c7e016e03247a3bf2d13348fe959fe6f436c1caf64c...,1008.0,0.12789
1,2dac0150717d,39aeb48f0017,Самарская область,Самара,Для дома и дачи,Мебель и интерьер,Другое,NaN,NaN,Стойка для Одежды,"Стойка для одежды, под вешалки. С бутика.",3000.0,19,2017-03-26,Private,79c9392cc51a9c81c6eb91eceb8e552171db39d7142700...,692.0,0.00000
2,ba83aefab5dc,91e2f88dd6e3,Ростовская область,Ростов-на-Дону,Бытовая электроника,Аудио и видео,"Видео, DVD и Blu-ray плееры",NaN,NaN,Philips bluray,"В хорошем состоянии, домашний кинотеатр с blu ...",4000.0,9,2017-03-20,Private,b7f250ee3f39e1fedd77c141f273703f4a9be59db4b48a...,3032.0,0.43177
3,02996f1dd2ea,bf5cccea572d,Татарстан,Набережные Челны,Личные вещи,Товары для детей и игрушки,Автомобильные кресла,NaN,NaN,Автокресло,Продам кресло от0-25кг,2200.0,286,2017-03-25,Company,e6ef97e0725637ea84e3d203e82dadb43ed3cc0a1c8413...,796.0,0.80323
4,7c90be56d2ab,ef50846afc0b,Волгоградская область,Волгоград,Транспорт,Автомобили,С пробегом,ВАЗ (LADA),2110,"ВАЗ 2110, 2003",Все вопросы по телефону.,40000.0,3,2017-03-16,Private,54a687a3a0fc1d68aed99bdaaf551c5c70b761b16fd0a2...,2264.0,0.20797
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,401d5fa8e55d,b5fe6a389cc4,Ярославская область,Ярославль,Хобби и отдых,Спорт и отдых,Игры с мячом,NaN,NaN,Продам бутсы Adidas,продам бутсы в отличном состоянии.отыграл 3 тр...,NaN,27,2017-03-27,Private,7c640fb4b6b4066c54e082193b66bedaedfee5e4d12975...,640.0,0.00000
996,4b136de2c16a,f57df929a284,Воронежская область,Воронеж,Бытовая электроника,"Игры, приставки и программы",Игры для приставок,NaN,NaN,Продам диск lara croft на psp,NaN,350.0,142,2017-03-27,Company,0a7686a2e05ca2dc0470e550f1f03b1eddee7919d363ca...,2888.0,0.00000
997,a65090f39f50,8673d0037023,Свердловская область,Монетный,Недвижимость,"Дома, дачи, коттеджи",Продам,Коттедж,NaN,Коттедж 150 м² на участке 12 сот.,Продается чудесный коттедж в экологически чист...,5900000.0,5830,2017-03-18,Shop,9061df217dd8f2b338e2645d52b09af6143677d011002a...,1376.0,0.07725
998,53e0aa75cecd,fbfe3f73586d,Башкортостан,Ишимбай,Транспорт,Автомобили,С пробегом,Hyundai,i30,"Hyundai i30, 2012",Продается автомобиль Hyundai i30. Был куплен ...,550000.0,1,2017-03-20,Private,c7fe551884576cb8b1bb9bbfe216b3e0b437d6b2208deb...,1118.0,0.10521
999,211a7d242f97,b3e017bd61eb,Самарская область,Самара,Для дома и дачи,Ремонт и строительство,Окна и балконы,NaN,NaN,Породам окно,"Глухое 1кам32 с.пакет, ш650в1440. Новое не под...",2000.0,32,2017-03-24,Private,a68483a58dfbf3b7abf95dfe623651aa45dc211dbb2992...,1405.0,0.00000

In [113]:
print("df.shape: {}".format(df.shape))
print("items_with_price.shape: {}".format(items_with_price.shape))

df.shape: (1000, 18)
items_with_price.shape: (1000, 18)

In [114]:
(np.nan == np.nan) / 1

0.0

In [115]:
np.nan != np.nan

True

In [117]:
df['price'].isna()

0      False
1      False
2      False
3      False
4      False
       ...
995     True
996    False
997    False
998    False
999    False
Name: price, Length: 1000, dtype: bool

In [118]:
np.sum(df['price'].isna())

65

In [119]:
df['price'].notna()

0       True
1       True
2       True
3       True
4       True
       ...
995    False
996     True
997     True
998     True
999     True
Name: price, Length: 1000, dtype: bool

In [121]:
df_without_nan = df.loc[df['price'].notna()]

In [122]:
print("np.nan + 1 = {}".format(np.nan + 1))
print("np.nan - 1 = {}".format(np.nan - 1))
print("np.nan * 1 = {}".format(np.nan * 1))
print("np.nan / 1 = {}".format(np.nan / 1))
print("np.sum([np.nan, 1]) = {}".format(np.sum([np.nan, 1])))
arr = np.array([np.nan, 1, 2, 3, np.nan])
print("arr.sum() = {}".format(arr.sum()))

np.nan + 1 = nan
np.nan - 1 = nan
np.nan * 1 = nan
np.nan / 1 = nan
np.sum([np.nan, 1]) = nan
arr.sum() = nan

In [123]:
df['price'].sum()

269889239.0

In [124]:
df['price'].sum(skipna=False)

nan

In [125]:
df_dropna = df.dropna(axis=0)
df_dropna.shape

(356, 18)

In [126]:
df['price'].fillna(0)

0          400.0
1         3000.0
2         4000.0
3         2200.0
4        40000.0
         ...
995          0.0
996        350.0
997    5900000.0
998     550000.0
999       2000.0
Name: price, Length: 1000, dtype: float64

In [127]:
df['price'].fillna(df['price'].mean())

0      4.000000e+02
1      3.000000e+03
2      4.000000e+03
3      2.200000e+03
4      4.000000e+04
           ...
995    2.886516e+05
996    3.500000e+02
997    5.900000e+06
998    5.500000e+05
999    2.000000e+03
Name: price, Length: 1000, dtype: float64

In [133]:
arr_ts = [
    0.469112,
    np.nan,
    -5.689738,
    np.nan,-8.916232

]

dates = [
    pd.Timestamp('2000-01-31'),
    pd.Timestamp('2000-02-29'),
    pd.Timestamp('2002-07-31'),
    pd.Timestamp('2005-01-31'),
    pd.Timestamp('2008-04-30')
]

ts = pd.Series(arr_ts, index=dates)
print(ts.index)
ts

DatetimeIndex(['2000-01-31', '2000-02-29', '2002-07-31', '2005-01-31',
               '2008-04-30'],
              dtype='datetime64[ns]', freq=None)

2000-01-31    0.469112
2000-02-29         NaN
2002-07-31   -5.689738
2005-01-31         NaN
2008-04-30   -8.916232
dtype: float64

In [130]:
ts.interpolate()

2000-01-31    0.469112
2000-02-29   -2.610313
2002-07-31   -5.689738
2005-01-31   -7.302985
2008-04-30   -8.916232
dtype: float64

In [134]:
ts.interpolate(method="time")

2000-01-31    0.469112
2000-02-29    0.273271
2002-07-31   -5.689738
2005-01-31   -7.095568
2008-04-30   -8.916232
dtype: float64

## The assert Statement

print("use of assert statement")
def negativecheck(number):
    assert(number>=0), "OOPS...Negative Number"
    print(number*number)
print(negativecheck(100))
print(negativecheck(-350))

## Using try..Except block

In [143]:
print ("Practicing for try block")
try:
    numerator=50
    denom=int(input("Enter the denominator"))
    quotient=(numerator/denom)
    print(quotient)
    print ("Division performed successfully")
except ZeroDivisionError:
    print ("Denominator as ZERO.... not allowed")
print("OUTSIDE try..except block")

Practicing for try block

Enter the denominator 2

25.0
Division performed successfully
OUTSIDE try..except block

## Multiple Exception

In [146]:
print ("Handling multiple exceptions")
try:
    numerator=50
    denom=int(input("Enter the denominator: "))
    print (numerator/denom)
    print ("Division performed successfully")
except ZeroDivisionError:
    print ("Denominator as ZERO is not allowed")
except ValueError:
    print("Only INTEGERS should be entered")

Handling multiple exceptions

Enter the denominator:  2

25.0
Division performed successfully

In [149]:
print ("Handling exceptions without naming them")
try:
    numerator=50
    denom=int(input("Enter the denominator"))
    quotient=(numerator/denom)
    print ("Division performed successfully")
except ValueError:
    print ("Only INTEGERS should be entered")
except:
    print(" OOPS.....SOME EXCEPTION RAISED")

Handling exceptions without naming them

Enter the denominator janhavi

Only INTEGERS should be entered

## Use of else clause

In [150]:
print ("Handling exception using try...except...else")
try:
    numerator=50
    denom=int(input("Enter the denominator: "))
    quotient=(numerator/denom)
    print ("Division performed successfully")
except ZeroDivisionError:
    print ("Denominator as ZERO is not allowed")
except ValueError:
    print ("Only INTEGERS should be entered")
else:
    print ("The result of division operation is ", quotient)

Handling exception using try...except...else

Enter the denominator:  23

Division performed successfully
The result of division operation is  2.1739130434782608

## Finally clause

In [151]:
print ("Handling exception using try...except...else...finally")
try:
    numerator=50
    denom=int(input("Enter the denominator: "))
    quotient=(numerator/denom)
    print ("Division performed successfully")
except ZeroDivisionError:
    print ("Denominator as ZERO is not allowed")
except ValueError:
    print ("Only INTEGERS should be entered")
else:
    print ("The result of division operation is ", quotient)
finally:
    print ("OVER AND OUT")

Handling exception using try...except...else...finally

Enter the denominator:  23

Division performed successfully
The result of division operation is  2.1739130434782608
OVER AND OUT

In [156]:
# Write a program to find if the product of consequective number in a list is x
# x = 210
# find:(5*6*7 == x)

In [161]:
list = [-4,5,6,-2,7,120]
x = 210

def consecutive_product(list, x):
    for i in range(len(list) - 2):
        product = list[i] * list[i + 1] * list[i + 2]
        if product == x:
            return True
    return False

if consecutive_product(list, x):
    print(f"The product of three consecutive numbers in the list equals to {x}.")
else:
    print(f"No three consecutive numbers in the list have a product that equals to {x}.")

No three consecutive numbers in the list have a product that equals to 210.

In [168]:
list = [-4,5,6,-2,7,120]

def cons(lis):
    newlist = []
    for i in range(1,len(lis)):
        if (lis[i]-lis[i-1])==1:
            newlis.append(lis[i-1])
            newlis.append(lis[i])
        else:
            for j in range(len(newlis)):
                if(lis[i] - newlis[j]==1):
                    newlist.append(lis[i])
        return newlis